### ISSUE TITLE
[scp] updater roadmap

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/server-control-panel#4]
**Todo** 

**Downloading**
- [ ] **extend server-control-panel with an updater**
  - [x] add button "updater" to main screen and to the tray
  - [x] add update dialog
  - [x] use table widget 
  - [x] fetch registry as JSON via API
  - [ ] scan local installation folder and build "local repository of installed software" as JSON
  - [ ] compare versions - using json API against json "local repository" 
  - [x] populate table accordingly
  - [x] allow download of components 
    - [x] add button "download"
    - [ ] if newer version is available, show update indication  
      - use a disabled green button 
  - [x] after the download of a component
    - [ ] enable the "update" button, when the download arrived
    - [x] change the "download" button to "install", when the download arrived
      - in other words: you can download multiple components in parallel 
      - and you trigger the update and install scripts individually afterwards
    - [ ] if new component, bind button to trigger the "install" script
    - [ ] if update component, bind button to trigger the "update" script
- [x] **extend server-control-panel with a downloader**
  - [x] add new class 
  - [x] handle multiple requests
  - [x] show progress for downloads
- [ ] ~~**add "downloads in progress" lock file as a guard**~~ not needed, download only from SCP
  - check for this file, before running update on the webinterface or the SCP
  - to prevent running update operations at the same time
  - set guard before download operation
    - [ ] from SCP
    - [ ] from webinterface
  - remove guard after download operation
    - [ ] from SCP
    - [ ] from webinterface
- [ ] ~~**webinterface**~~ - not needed, download only from SCP
  - [ ] drop the curl based downloader in the webinterface
    - the callback is crappy and hackish, because PHP simply doesn't support this kinda of functionality very well
  - [ ] check, if we can integrate guzzle for parallel fetching
    - either in the webinterface or in the task-runner
  - [ ] else simply ship aria and use `aria -i downloads.txt`
    - check, if we can integrate aria into the task-runner (packaged phar)
- [x] use `bin\downloads` as the target folder for downloads
  - we can't use temp, because the folder is under session auto-cleanup from the start cmd

**Installing and Updating**
- [x] add install and update scripts
  - CLI scripts executed via the task-runner #471: `do update <component>` - `do install <component>`
  - we could extend or reuse functionality of the component classes from the webinterface
    - https://github.com/WPN-XM/webinterface/tree/master/php/Components
  - some of the install tasks can simply re-use the installation steps taken by the innosetup scripts
  - the update steps have to be written freshly
  - we probably need either "before" and "after" action event binding, to allow for instance "backup" to happen before updating or a state system with install steps
  - all install and update scripts are handled as individual issues

**Blocked by**
- [ ] task-runner #471 
##
